import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import brentq

RECOVERY_RATE = 0.4
LGD = 1 - RECOVERY_RATE

def survival_probs(hazard_rates, times):

    if np.any(np.isnan(hazard_rates)):
        raise ValueError("Invalid hazard curve")

    q = [1.0]
    for i in range(len(times)):
        dt = times[i] - (times[i-1] if i > 0 else 0.0)
        lam = hazard_rates[i]
        q.append(q[-1] * np.exp(-lam * dt))
    return q[1:]

def cds_equation(lamb, known_lambdas, times, dfs, spread):
        """Computes CDS pricing equation (premium - protection leg)"""     

        lambdas = known_lambdas + [lamb]
        q = survival_probs(lambdas, times)

        premium_leg = 0.0
        protection_leg = 0.0

        df_values = dfs["Discount Factor"]

        for i, t in enumerate(times):
            dt = t - (times[i-1] if i > 0 else 0.0)

            premium_leg += spread * df_values.loc[t] * q[i] * dt

            q_prev = q[i-1] if i > 0 else 1.0
            protection_leg += LGD * df_values.loc[t] * (q_prev - q[i])

        return premium_leg - protection_leg

def main():

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    DATA_PATH = os.path.join(BASE_DIR, "data", "raw", "market_data2.xlsx")
    OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    data = pd.read_excel(DATA_PATH,
                        header = 1,
                        index_col= 0,
                        usecols= 'B:H',
                        nrows = 11)
    data = data.sort_index()

    DFS_PATH = os.path.join(BASE_DIR, "data", "processed", "discount_factors.csv")
    dfs = pd.read_csv(DFS_PATH, index_col= 0) #Load discount factors generated by zcb_curve.py
    dfs = dfs.sort_index()
    dfs.index = dfs.index.astype(float)

    maturities = data.index.to_numpy(dtype = float)
    assert all(t in dfs.index for t in maturities), "Mismatch between CDS maturities and discount factors"
    hazard_rates = {}

    for firm in data.columns:
        spreads = {t: data.loc[t, firm] / 10000 for t in maturities}

        lambdas = []

        for i, t in enumerate(maturities):
            times = maturities[:i+1]
            spread = spreads[t]

            try:
                lam = brentq(
                    cds_equation,
                    a=1e-6,
                    b=5.0,
                    args=(lambdas, times, dfs, spread),
                    maxiter=200
                )
            except ValueError as e:
                raise RuntimeError(
                    f"Root finding failed for {firm} at maturity {t}."
                    "Check spreads / discount factors / initial curve."
                )
            
            lambdas.append(lam)

        hazard_rates[firm] = lambdas

    hazard_rates_table = pd.DataFrame(hazard_rates, index=maturities)

    print("\nHazard Rates DataFrame:")
    print(hazard_rates_table)

    survival_probabilities = {}
    default_probabilities = {}
    for firm in hazard_rates_table.columns:
        lambdas = hazard_rates_table[firm].to_numpy()
        times = hazard_rates_table.index.to_numpy()

        q = survival_probs(lambdas, times)

        survival_probabilities[firm] = q
        default_probabilities[firm] = 1 - np.array(q)

    survival_probabilities_table = pd.DataFrame(survival_probabilities,
                                                index=maturities)

    default_probabilities_table = pd.DataFrame(default_probabilities,
                                            index=maturities)

    print("\nSurvival Probabilities DataFrame:")
    print(survival_probabilities_table)

    print("\nDefault Probabilities DataFrame:")
    print(default_probabilities_table)

    fig, ax = plt.subplots()
    for firm in survival_probabilities_table.columns:
        ax.plot(maturities,
                survival_probabilities_table[firm],
                label=f'Survival - {firm}')
    ax.set_xlabel('Maturity (years)')
    ax.set_ylabel('Survival Probability')
    ax.set_title('Survival Probabilities over Time')
    ax.legend()
    ax.grid()
    plt.savefig(os.path.join(OUTPUT_DIR, "survival_probabilities_plot.png"))

    fig, ax = plt.subplots()
    for firm in default_probabilities_table.columns:
        ax.plot(maturities,
                default_probabilities_table[firm],
                label=f'Default - {firm}') 
    ax.set_xlabel('Maturity (years)')
    ax.set_ylabel('Default Probability')
    ax.set_title('Default Probabilities over Time')
    ax.legend()
    ax.grid()
    plt.savefig(os.path.join(OUTPUT_DIR, "default_probabilities_plot.png"))

    hazard_rates_table.to_csv(os.path.join(OUTPUT_DIR, "hazard_rates.csv"))
    survival_probabilities_table.to_csv(os.path.join(OUTPUT_DIR, "survival_probabilities.csv"))
    default_probabilities_table.to_csv(os.path.join(OUTPUT_DIR, "default_probabilities.csv"))

    plt.show()


if __name__ == "__main__":
    main()